spring:
    datasource:
        url: jdbc:mysql://localhost:3306/pfs
        username: root
        password: 12345678
        driver-classname: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: false
        properties:
            hibernate:
                format_sql: true
        database: mysql
        database-platform: org.hibernate.dialect.MySQLDialect
        open-in-view: false
    mail:
        host: smtp.gmail.com
        port: 587
        username: mohcine.sahtani@gmail.com
        password: flhehemnqboxppaz
        protocol: smtp
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true