### SIGNING AS ADMIN
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "admin@movingservice.ma",
  "password": "12345678"
}

### ACCEPT AN PROVIDER
PUT http://localhost:8080/api/v1/provider/2/accept
Authorization: {{adminToken}}
