### SIGNUP AS CLIENT
POST http://localhost:8082/api/v1/auth/login
Content-Type: application/json

{
  "email": "mohcine.sahtani@gmail.com",
  "password": "12345678"
}

### SIGNIN AS CLIENT WITH WRONG CRIDENTIAL
POST http://localhost:8082/api/v1/auth/login
Content-Type: application/json

{
  "email": "mohcine.sahtani@gmail.com",
  "password": "12345678"
}

### ADD AN DEMAND
POST http://localhost:8082/api/v1/demand
Content-Type: application/json
Authorization: {{clientToken}}

{
    "when": "2023-01-19 10:00",
    "from": "Safi",
    "to": "Marrakech",
    "description": "some description",
    "proposedPrice": "400"
}

### ADD ANOTHER DEMAND
POST http://localhost:8080/api/v1/demand
Content-Type: application/json
Authorization: {{clientToken}}

{
  "title": "moving from safi to Essaouira",
  "from": "Safi",
  "to": "Essaouira",
  "description": "some description",
  "proposedPrice": "200"
}