### SIGNUP AS PROVIDER
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "fullName": "siham sahtani",
  "email": "sihamsahtani@gmail.com",
  "phoneNumber": "+212704261627",
  "password": "12345678",
  "city": "Safi"
}

### GET DEMANDS FOR THE PROVIDER
GET http://localhost:8080/api/v1/demand
Authorization: {{providerToken}}


### GET PROVIDER PROFILE
GET http://localhost:8080/api/v1/provider/3
Authorization: {{clientToken}}